### PR TITLE
Update to use new Control.Lens

### PR DESCRIPTION
**Pull request by adinapoli**
Hi all,

I've updated the code to be compliant with the new Lens library which Snap uses.
My only doubt is that probably this line could be simplified, but I'm still new to the new lens package:

https://github.com/adinapoli/snaplet-mongodb-minimalistic/pull/new/master#L0R26

ideas?

### CODE REVIEW

**Comment by adinapoli** [comment]
any chance this patch will be merged eventually? @Palmik

**Comment by adinapoli** [comment]
@Palmik sorry for pestering you, but I really suggest you merge this patch :) It will allow to use this module with the current version of Snap, otherwise making this package useless :P 

A.

**Comment by Palmik** [comment]
You are not pestering me at all. Again, thank you for your patch, sorry I took so long to merge it.

**Comment by adinapoli** [comment]
No worries, thanks for merging it and for your fine snaplet :)

A.

**Pull request merged**
